# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright (c) 2025 Stefan Wold <ratler@stderr.eu>

version: '3.8'

services:
  airuler:
    image: ratler/airuler:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ["--help"]

  # Service for compiling templates
  compile:
    image: ratler/airuler:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ["compile"]

  # Service for watching templates during development
  watch:
    image: ratler/airuler:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ["watch"]